# Generated by Django 2.0.2 on 2018-03-27 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='会议室名称')),
                ('num', models.IntegerField(verbose_name='容纳人数')),
                ('des', models.CharField(max_length=64, verbose_name='会议室介绍')),
            ],
        ),
        migrations.CreateModel(
            name='OrderRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField(auto_now_add=True, verbose_name='预定日期')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_area', models.CharField(max_length=32, verbose_name='时间段')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
            ],
        ),
        migrations.AddField(
            model_name='orderrecord',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.UserInfo', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='orderrecord',
            name='meet_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.MeetingRoom', verbose_name='会议室'),
        ),
        migrations.AddField(
            model_name='orderrecord',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.TimeSlot'),
        ),
        migrations.AlterUniqueTogether(
            name='orderrecord',
            unique_together={('meet_room', 'order_time', 'time_slot')},
        ),
    ]
