# Generated by Django 2.0.2 on 2018-03-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingroom',
            name='des',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='会议室介绍'),
        ),
        migrations.AlterField(
            model_name='orderrecord',
            name='order_time',
            field=models.DateField(verbose_name='预定日期'),
        ),
    ]
