# Generated by Django 2.0.2 on 2018-03-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20180328_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrecord',
            name='col',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='列'),
        ),
        migrations.AddField(
            model_name='orderrecord',
            name='row',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='行'),
        ),
    ]
